### ISSUE TITLE
start redis fails with memory address

### ISSUE THREAD

**Issue by gedw99** [mirzakhany/dbctl#32]
I am using latest and on Mac M2 arm....

docker is running using Orbstack and works fine.

https://orbstack.dev

```sh
./dbctl start redis
2024/04/25 09:13:44 Starting redis version 7.0.4 on port 16379 ...
2024/04/25 09:13:44 INFO: Pulling docker image: "redis:7.0.4-bullseye", depends on your connection speed it might take upto minutes
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10337b78c]

goroutine 1 [running]:
github.com/mirzakhany/dbctl/internal/database/redis.(*Redis).Start(0x140000cf100, {0x1035a5d48, 0x14000288000}, 0x0)
	/home/runner/work/dbctl/dbctl/internal/database/redis/redis.go:147 +0x20c
github.com/mirzakhany/dbctl/cmd/start.runRedis(0x14000214000?, {0x1033df0e6?, 0x0?, 0x0?})
	/home/runner/work/dbctl/dbctl/cmd/start/redis.go:76 +0x3c8
github.com/spf13/cobra.(*Command).execute(0x14000214000, {0x140000981a0, 0x0, 0x0})
	/home/runner/work/dbctl/dbctl/vendor/github.com/spf13/cobra/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x1400017f680)
	/home/runner/work/dbctl/dbctl/vendor/github.com/spf13/cobra/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/dbctl/dbctl/vendor/github.com/spf13/cobra/command.go:918
main.main()
	/home/runner/work/dbctl/dbctl/main.go:33 +0x304

```

**Comment by gedw99** [comment]
for postres I get 

```sh
./dbctl start postgres
2024/04/25 09:16:42 INFO: Starting postgres version 13-3.1 on port 15432 ...
2024/04/25 09:16:42 INFO: Pulling docker image: "odidev/postgis:13-3.1-alpine", depends on your connection speed it might take upto minutes
Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

```

docker is there 

```sh
docker pull postgres:14.5
14.5: Pulling from library/postgres
dd6189d6fc13: Pull complete 
e83a243abe4a: Pull complete 
e1e5d0e9701b: Pull complete 
b8172b349685: Pull complete 
83dad09f3014: Pull complete 
c4849d0ca437: Pull complete 
7642d443be37: Pull complete 
a40f15729374: Pull complete 
0d91bb9f75c8: Downloading [====>                                              ]  8.066MB/87.86MB
11d50fc375b9: Download complete 
58770f84c28e: Download complete 
c66c6cdaad21: Download complete 
```

**Comment by gedw99** [comment]
Might be this, but not sure yet

https://docs.orbstack.dev/docker/#docker-context-socket

**Comment by mirzakhany** [comment]
Hi @gedw99 sorry for responding late. This is a docker desktop issue on macOS . You need to enable default docker socket in it’s settings
